[package]
name = "draco-reputation"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
draco-interfaces = {path="../interfaces"}
fleek-crypto.workspace = true
hp-fixed.workspace = true

[dev-dependencies]
draco-test-utils = {path="../test-utils"}
rand.workspace = true

