[package]
name = "lightning-utils"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
autometrics.workspace = true
lightning-interfaces = { path = "../interfaces" }
anyhow.workspace = true
tokio.workspace = true
tracing.workspace = true
ethers.workspace = true
fleek-crypto.workspace = true
serde.workspace = true
serde_json.workspace = true
reqwest.workspace = true
resolved-pathbuf.workspace = true
toml = "0.7"
workspace-hack = { version = "0.1", path = "../../etc/workspace-hack" }
lazy_static.workspace = true
