[package]
name = "lightning-utils"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
autometrics.workspace = true
lightning-interfaces = { path = "../interfaces" }
lightning-types.workspace = true
anyhow.workspace = true
tokio.workspace = true
tracing.workspace = true
ethers.workspace = true
fleek-crypto.workspace = true
serde.workspace = true
serde_json.workspace = true
reqwest.workspace = true
