[package]
name = "lightning-types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde.workspace = true
ink-quill.workspace = true
fleek-crypto.workspace = true
hp-fixed.workspace = true
multiaddr = "0.17.1"
num-bigint = { workspace = true, features=["serde"]}
num-traits.workspace = true
num-derive.workspace = true
derive_more = "0.99"
