[package]
name = "global-metrics"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
axum = { version = "0.6.20", features=["macros"] }
bincode = "1.3.3"
dotenv= "0.15.0"
geohash = "0.13.0"
geo-types = "0.7.11"
hyper = "0.14.27"
hyper-tls = "0.5.0"
lazy_static = "1.4.0"
lightning-types = { git = "https://github.com/fleek-network/lightning.git", branch = "b/add-registry-with-index"}
maxminddb = "0.23.0"
moka = { version = "0.11", features = ["sync"] }
serde = {version = "1.0.188", features = ["derive"]}
serde_derive = "1.0.186"
serde_json = "1.0.105"
sled = "0.34.7"
tokio = { version = "1.28", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3.17"

resolved-pathbuf = "0.1.3"
