chain_id = 59330
epoch_start = 1710342463451
epoch_time = 1800000
committee_size = 6
min_stake = 1000
eligibility_time = 1
lock_time = 5
protocol_share = 0
node_share = 80
service_builder_share = 20
max_inflation = 10
consumer_rebate = 0
max_boost = 4
max_lock_time = 1460                                                 # 1460 days(epoch) meaning 4 years
supply_at_genesis = 1000000                                          # set to 1 million for testing, to be determined when initial allocations are set
protocol_fund_address = "0x2a8cf657769c264b0c7f88e3a716afdeaec1c318"
governance_address = "0x2a8cf657769c264b0c7f88e3a716afdeaec1c318"

[[node_info]]
owner = "0x2a8cf657769c264b0c7f88e3a716afdeaec1c318"
primary_public_key = "9MwDMXsqg78qSTnQU5h6oX2EcrNmJEsDebffibkDG3Kd"
consensus_public_key = "22dEun7hCf6u44JWgwEEduXFrcjbGDsBE9jn5GmzKHvodnxGNPB9hwHXwtAL6r1A9Vrn4yAaPrKAUHSxHEP3WYvBBBxmbCLBMybqSEsXp2NVpHsAaZiiC3x2De1MmD1q8ijS"
worker_public_key = "9MwDMXsqg78qSTnQU5h6oX2EcrNmJEsDebffibkDG3Kd"
primary_domain = "15.204.100.218"
worker_domain = "15.204.100.218"
ports.primary = 4310
ports.worker = 4311
ports.mempool = 4210
ports.rpc = 4240
ports.pool = 4300
ports.pinger = 4350
ports.handshake.http = 4220
ports.handshake.webrtc = 4320
ports.handshake.webtransport = 4321
stake.staked = "1000"
stake.stake_locked_until = 0
stake.locked = "0"
stake.locked_until = 0
genesis_committee = true

[[node_info]]
owner = "0x2a8cf657769c264b0c7f88e3a716afdeaec1c318"
primary_public_key = "GPtFwnMdfGxtozF7R8ZszQzGZpeqxRb1RZ5cZkmRYwb8"
consensus_public_key = "25ZW4HczNusjgXuDsHRG8vBWE3QsqmQg6qt2Htr7AMKXx849wWucAFhN3T2JD67cUJc7QGFLjKTzxMctniPjZ2BXWqgtUZuJ3YT89fPohQibS3pruvnTdnmLDVtizJba834f"
worker_public_key = "GPtFwnMdfGxtozF7R8ZszQzGZpeqxRb1RZ5cZkmRYwb8"
primary_domain = "15.204.222.16"
worker_domain = "15.204.222.16"
ports.primary = 4310
ports.worker = 4311
ports.mempool = 4210
ports.rpc = 4240
ports.pool = 4300
ports.pinger = 4350
ports.handshake.http = 4220
ports.handshake.webrtc = 4320
ports.handshake.webtransport = 4321
stake.staked = "1000"
stake.stake_locked_until = 0
stake.locked = "0"
stake.locked_until = 0
genesis_committee = true

[[node_info]]
owner = "0x2a8cf657769c264b0c7f88e3a716afdeaec1c318"
primary_public_key = "2jxdUis16voo7vXKd9FRPAcpr4EDQcbnvcW4F19z8CjR"
consensus_public_key = "z5RaeajLPGAxRFUkREwsCp3HB8t3sswPTo3XLHZFo447NDEhw1WfNfzpwJXTEMBznQX7jJ9HwELoNquWCMa4eT5QcCkksiRSEkZiK9qTLeMg4C8XhqgM4i5cVPsRfdFeXbt"
worker_public_key = "2jxdUis16voo7vXKd9FRPAcpr4EDQcbnvcW4F19z8CjR"
primary_domain = "57.128.193.76"
worker_domain = "57.128.193.76"
ports.primary = 4310
ports.worker = 4311
ports.mempool = 4210
ports.rpc = 4240
ports.pool = 4300
ports.pinger = 4350
ports.handshake.http = 4220
ports.handshake.webrtc = 4320
ports.handshake.webtransport = 4321
stake.staked = "1000"
stake.stake_locked_until = 0
stake.locked = "0"
stake.locked_until = 0
genesis_committee = true

[[node_info]]
owner = "0x2a8cf657769c264b0c7f88e3a716afdeaec1c318"
primary_public_key = "5Drki1M3VGVYiKgdb5PUJXzv5qcVjQ81hCzWeKd8PjiS"
consensus_public_key = "sz1KNJyfitotzg2n7kJeyZfdkdgChdRBxEu9wiTyz7CVvAiehNFVg8VRL3TFMK5airXcTgMQ1YVBL12f1dzTUzUm6XBDDzmxTxtKzCghRykPHdAXXSsP9rPar5Le9bHnJin"
worker_public_key = "5Drki1M3VGVYiKgdb5PUJXzv5qcVjQ81hCzWeKd8PjiS"
primary_domain = "57.128.175.56"
worker_domain = "57.128.175.56"
ports.primary = 4310
ports.worker = 4311
ports.mempool = 4210
ports.rpc = 4240
ports.pool = 4300
ports.pinger = 4350
ports.handshake.http = 4220
ports.handshake.webrtc = 4320
ports.handshake.webtransport = 4321
stake.staked = "1000"
stake.stake_locked_until = 0
stake.locked = "0"
stake.locked_until = 0
genesis_committee = true

[[node_info]]
owner = "0x2a8cf657769c264b0c7f88e3a716afdeaec1c318"
primary_public_key = "4vmaPja4E1hG4qsmNN8GSJi97PRPLRzDjS9iqpNqyggz"
consensus_public_key = "sEYALxkymfAxnoYiosWj2AadEbhg9c8c5iCkcGuWrnJAP9G1aTQZQZytH2saqhg5SVJJ4H1QjHudaJHxNDRUpRYZAnpX3jAuDxN5P949DPi2VashX4UJUdKHCRvahiWjDya"
worker_public_key = "4vmaPja4E1hG4qsmNN8GSJi97PRPLRzDjS9iqpNqyggz"
primary_domain = "162.19.99.30"
worker_domain = "162.19.99.30"
ports.primary = 4310
ports.worker = 4311
ports.mempool = 4210
ports.rpc = 4240
ports.pool = 4300
ports.pinger = 4350
ports.handshake.http = 4220
ports.handshake.webrtc = 4320
ports.handshake.webtransport = 4321
stake.staked = "1000"
stake.stake_locked_until = 0
stake.locked = "0"
stake.locked_until = 0
genesis_committee = true

[[node_info]]
owner = "0x2a8cf657769c264b0c7f88e3a716afdeaec1c318"
primary_public_key = "Dr1YbaXoYjzZnM7suh1qJ71ZEBsyFzbT3rdxZ4wkPGtz"
consensus_public_key = "21sU1LgUwSzQFrPruEQYRPjLqYxY1pSUAk61GUrn1jU7qUHBkY7iQRjQrGLdpETU87xic3huqVNMfBD6CXJQrK6kWTAe49nmgbzK8ZTexEccda16W7MVGcjoBnDWSNnmGUGw"
worker_public_key = "Dr1YbaXoYjzZnM7suh1qJ71ZEBsyFzbT3rdxZ4wkPGtz"
primary_domain = "141.94.219.127"
worker_domain = "141.94.219.127"
ports.primary = 4310
ports.worker = 4311
ports.mempool = 4210
ports.rpc = 4240
ports.pool = 4300
ports.pinger = 4350
ports.handshake.http = 4220
ports.handshake.webrtc = 4320
ports.handshake.webtransport = 4321
stake.staked = "1000"
stake.stake_locked_until = 0
stake.locked = "0"
stake.locked_until = 0
genesis_committee = true

[[node_info]]
owner = "0x2a8cf657769c264b0c7f88e3a716afdeaec1c318"
primary_public_key = "HkAXaMqczrC9NPxyhJ59KnSqBQU96o8qnW6urDaCPw3P"
consensus_public_key = "nuRhivVwS8YsvNcNhBwVybdPh4AJRvrWix1gkhicBUmNfzkko1q5rNpEuCrVghU3jKNGKpcsHeWwYrBFavoynCNRCf2WjEM36TqxQ5WjwwYySVnBApF7vdcFDhQcBPa1WiZ"
worker_public_key = "HkAXaMqczrC9NPxyhJ59KnSqBQU96o8qnW6urDaCPw3P"
primary_domain = "141.95.64.216"
worker_domain = "141.95.64.216"
ports.primary = 4310
ports.worker = 4311
ports.mempool = 4210
ports.rpc = 4240
ports.pool = 4300
ports.pinger = 4350
ports.handshake.http = 4220
ports.handshake.webrtc = 4320
ports.handshake.webtransport = 4321
stake.staked = "1000"
stake.stake_locked_until = 0
stake.locked = "0"
stake.locked_until = 0
genesis_committee = true

[[node_info]]
owner = "0x2a8cf657769c264b0c7f88e3a716afdeaec1c318"
primary_public_key = "3chd1Bbpg7tVFU7sNfifkgLFcFcDXZJ2G2Mjc5kUJg6h"
consensus_public_key = "yGTjCb8ujCD1ayryqn5nXUYW6oFbmPi2enSnvUKC2ruZvuBL1HQrJ5LWSENGYhd7m1tAXo8BFUuAHmPLD922GruMUMovERKYbF4b3stfQHa11vrLkPLmG56AN3Yf6mtcQG4"
worker_public_key = "3chd1Bbpg7tVFU7sNfifkgLFcFcDXZJ2G2Mjc5kUJg6h"
primary_domain = "57.128.101.139"
worker_domain = "57.128.101.139"
ports.primary = 4310
ports.worker = 4311
ports.mempool = 4210
ports.rpc = 4240
ports.pool = 4300
ports.pinger = 4350
ports.handshake.http = 4220
ports.handshake.webrtc = 4320
ports.handshake.webtransport = 4321
stake.staked = "1000"
stake.stake_locked_until = 0
stake.locked = "0"
stake.locked_until = 0
genesis_committee = true

[[node_info]]
owner = "0x2a8cf657769c264b0c7f88e3a716afdeaec1c318"
primary_public_key = "FoMVEHRSWhfEkPXgfxaRcxEVQFSchkJgM4wwxEo89251"
consensus_public_key = "215CXYBiz6qDvsgxiaQNqaTjbLM1Kuv85aniV1hgCwQJsiW5rFDjbDMUi7dS8Ere7gvvzbGL3ztybcPp2Kzi8h3wAiBBtGZE2HG6295fj8xyWGkeXeU7sNxFCesQrRwQf19a"
worker_public_key = "FoMVEHRSWhfEkPXgfxaRcxEVQFSchkJgM4wwxEo89251"
primary_domain = "15.235.55.115"
worker_domain = "15.235.55.115"
ports.primary = 4310
ports.worker = 4311
ports.mempool = 4210
ports.rpc = 4240
ports.pool = 4300
ports.pinger = 4350
ports.handshake.http = 4220
ports.handshake.webrtc = 4320
ports.handshake.webtransport = 4321
stake.staked = "1000"
stake.stake_locked_until = 0
stake.locked = "0"
stake.locked_until = 0
genesis_committee = true

[[node_info]]
owner = "0x2a8cf657769c264b0c7f88e3a716afdeaec1c318"
primary_public_key = "5ACw3pQKNduDM8TDQ35viiF3LRyKwZkrdYpck498F6Ce"
consensus_public_key = "xWrBKEC6f5x27EqTDNNzU3LJuV3taqsuX7jhd7rUndnGtB3dkxcTETyFkruS9NFYrSfHyco5kGLuJEEP5bpodFgM2y191K6WLyaeivJWVmwH1bMA3GHNt3o17veuL1V5WP2"
worker_public_key = "5ACw3pQKNduDM8TDQ35viiF3LRyKwZkrdYpck498F6Ce"
primary_domain = "148.113.16.100"
worker_domain = "148.113.16.100"
ports.primary = 4310
ports.worker = 4311
ports.mempool = 4210
ports.rpc = 4240
ports.pool = 4300
ports.pinger = 4350
ports.handshake.http = 4220
ports.handshake.webrtc = 4320
ports.handshake.webtransport = 4321
stake.staked = "1000"
stake.stake_locked_until = 0
stake.locked = "0"
stake.locked_until = 0
genesis_committee = true

[[service]]
id = 0
owner = "0xDC0A31F9eeb151f82BF1eE6831095284fC215Ee7"
commodity_type = "Bandwidth"

[[service]]
id = 1
owner = "0x684166BDbf530a256d7c92Fa0a4128669aFd9B9F"
commodity_type = "Compute"

[[account]]
public_key = "0x2a8cf657769c264b0c7f88e3a716afdeaec1c318"
flk_balance = "100690000000000000000"
stables_balance = 100
bandwidth_balance = 100

[[commodity_prices]]
commodity = "Bandwidth"
price = 0.1

[[commodity_prices]]
commodity = "Compute"
price = 1

[rep_scores]

[total_served]

[current_epoch_served]

[client]
