[package]
name = "lightning-resolver"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lightning-interfaces = { path = "../interfaces" }
anyhow.workspace = true
async-trait.workspace = true
bincode.workspace = true
fleek-crypto.workspace = true
tracing.workspace = true
resolved-pathbuf.workspace = true
serde.workspace = true
tokio.workspace = true
rocksdb = "0.21"
workspace-hack = { version = "0.1", path = "../../etc/workspace-hack" }

[dev-dependencies]
lightning-test-utils = { path = "../test-utils" }
lightning-signer = { path = "../signer" }
lightning-broadcast = { path = "../broadcast" }
lightning-rep-collector = { path = "../rep-collector" }
lightning-application = { path = "../application", features = ["test"] }
lightning-pool = { path = "../pool" }
lightning-notifier = { path = "../notifier" }
lightning-topology = { path = "../topology" }
fleek-crypto.workspace = true
tracing-test = { version = "0.2", features = ["no-env-filter"] }
