[package]
name = "lightning-openrpc"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
schemars = "0.8.16"
serde.workspace = true
serde_json.workspace = true
versions = "5.0.1"
lightning-workspace-hack.workspace = true
