[package]
name = "lightning-test-utils"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lightning-interfaces = { path = "../interfaces" }
async-trait.workspace = true
fleek-crypto.workspace = true
affair.workspace = true
axum.workspace = true
anyhow.workspace = true
rand.workspace = true
serde.workspace = true
tokio.workspace = true
hp-fixed.workspace = true
serde_json = "1.0"
