[package]
name = "lightning-origin-arweave"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lightning-interfaces = {path="../interfaces"}
anyhow.workspace = true
serde.workspace = true
